# Generated by Django 3.2.6 on 2023-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
