# Generated by Django 3.2.6 on 2023-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230519_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[('trip', 'trip'), ('purchase', 'purchase'), ('party', 'party'), ('other', 'other')], db_index=True, default='other'),
        ),
    ]
