# Generated by Django 3.2.6 on 2023-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, 'trip'), (2, 'purchase'), (3, 'party'), (4, 'other')], db_index=True, default=4),
        ),
    ]
