# Generated by Django 3.2.6 on 2023-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='split',
            field=models.JSONField(null=True),
        ),
    ]
