# Generated by Django 3.2.6 on 2023-05-29 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_spend_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
