# Generated by Django 3.2.6 on 2023-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_spend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
